before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: pkRJOXgekop4eWIhgWmy+5jwQ//X2KF0sxBsQzKYHuyUE6qxlZvm21xiTOlfQZPht0gyhVvfPqonN2oF1LX+2I/WYfBh3SW9OyKQtEZOJJBp6WXZEvni8ic6YqxJ+EzflUOzdSvVXSq8JcL7wcrN2aFe3cqurRZjmH9HDHZmpmizmUQBIJbAn8P1QRwWcWgk5dzq6h0Fv6iwyaXkiKzB151lGnn4pNUL/2jMhoeXHL9ZEwe1iHrRTpnwJfUvUZkLG9Xim1PjdJki5PN0cn5VMLBx7ubBSBjaC3L3RKeboPsj5w994OM0hscOYNxPZj3TEtZCqdwyXxYSZ6ZaumoZ4MqEPgeDHHHKE2+LIkP9JDmthSzWcOsIoqyqbgV0TNun3gql1gmoZHo02kkMZ8sWCBwf+Mt3qKodCDsnH4rK+HeWC1fGAOHMhgmjAuGJoDR+UN+C0mq3F9A90dcW5J+qbNBcwO+d4GebLRFXKWlXhVMO7N2KRnnNioI4xwz3N8j9Vsc1myVsS0Xh7JxEXpnlkPwJR5LWdErq6gzrzCgblTP7vhYH86E5GtflaiFY3q/4/OkqW2ZlNEU6mt1W6uNNlsVGfurwXuEieJORzzlF5MFRvimhFPUR8x0oa/w8GFGDA1rwxeVYXYd3G07cM4yNoclvjNMfgAvnaR9wJORcXq0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
